### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by Matt-Hurd**
I'm a professional, I swear.

Takes care of #17

Edit: Ignore the branch name

### CODE REVIEW

**Comment by akleemans** [comment]
I think the license file should better be called "LICENSE" (instead of the current "COPYING"), at least that what I'm used to usually on Github.

**Comment by Matt-Hurd** [comment]
Fair enough. I do want to keep both, so we go by both github and GNU standards.

**Comment by akleemans** [comment]
> Fair enough. I do want to keep both, so we go by both github and GNU standards.

Ah, didn't know about GNU. With that, I would probably just go with one file and only have the "COPYING" one (beware they get out of sync...). Sorry for complicating things :)

**Comment by Matt-Hurd** [comment]
No worries. I think that github will automatically add the license to the side even with it as `COPYING`

**Comment by BraydonKains** [comment]
> No worries. I think that github will automatically add the license to the side even with it as `COPYING`

I went through some GPL3 licensed repos and can confirm `COPYING` and `LICENSE` as the file name has the same GitHub functionality result.

**Review by akleemans — APPROVED** [review]
👌

**Pull request merged**
